USE lets_meet;

/*
 * |--------|
 * | Events |
 * |--------|
 */
CREATE PROCEDURE get_event_details(IN _url_id VARCHAR(255))
    SELECT id, title, description, dtime_created FROM event
    WHERE url_id = _url_id;

CREATE PROCEDURE get_event_intervals(IN _event_id INT)
    SELECT start_dtime, end_dtime FROM event_interval
    WHERE event_id = _event_id;

CREATE PROCEDURE get_event_users(IN _event_id INT)
    SELECT username, start_dtime, end_dtime FROM user_interval
    WHERE event_id = _event_id;

/*
 * Event intervals and user intervals need to be done with a batch insert.
 *
 * The url_id needs to be generated by the client with the new insert id.
 */
DELIMITER $$
CREATE PROCEDURE create_new_event(
        IN _title VARCHAR(255),
        IN _description VARCHAR(255),
        IN _username VARCHAR(255),
        IN _password CHAR(60))
    BEGIN
    INSERT INTO event (title, description) VALUES
        (_title, _description);
    SET @new_id := LAST_INSERT_ID();
    INSERT INTO event_user (event_id, username, password, is_admin) VALUES
        (@new_id, _username, _password, TRUE);
    SELECT @new_id;
    END$$
DELIMITER ;

/*
 * If url_id is not unique, throw (1062, "Duplicate entry <url_id> for key ...")
 */
CREATE PROCEDURE update_url_id(
        IN _id INT,
        IN _url_id VARCHAR(255))
    UPDATE event
        SET url_id = _url_id
        WHERE id = _id;

/*
 * |-------|
 * | Users |
 * |-------|
 */
CREATE PROCEDURE set_refresh_token(
        IN _event_id INT,
        IN _username VARCHAR(255),
        IN _refresh_token TEXT)
    UPDATE event_user
        SET refresh_token = _refresh_token
        WHERE event_id = _event_id
        AND username = _username;